### ISSUE TITLE
[Bug] Task completion streak lost when tasks were overdue

### ISSUE THREAD

**Issue by tbishop9** [Ayagikei/LifeUp#130]
**Describe the bug**
Had a 500+ day streak of task completion, which was lost when I forgot to mark off tasks on that day despite being done. 
When they popped up as overdue the next morning I completed them, but the streak was lost.

**To Reproduce**
1. Build a streak
2. Fail to tick tasks as complete on a given day
3. Mark as complete the next day when shown as overdue
4. Streak is lost, even though task completion date is shown as previous day

**Expected behavior**
Streak should only be lost if tasks are not completed

**Environments and Version (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - Version: Latest

**Comment by Ayagikei** [comment]
Hello,
The streak this question refers to should be the overall streak for the "Me" page.

It was developed in the early days of the app and currently has this problem, and it will strictly require tasks to be completed within the same day.

We will consider optimizing it.

We are sorry for the impact on your data. Since LifeUp is an offline application, we do not have a suitable way to directly help you make up for the previous data. But when we optimize, we will also consider whether there are ways to make up for it.

If you want to try to repair the data yourself, you can check to see if you have a backup file from the day before the streak broke.

Or try to use technical means - export backup - use the Sqlite editor to modify the corresponding data (data in the `recordmodel` table).

If you need to recover data urgently, you can also consider sending the backup file after ignoring the media files to us (email lifeup@ulives.io) to try to repair it and then import it again.

**Comment by tbishop9** [comment]
Thanks, I managed to export backup, edit the db as you suggested, imported back in - streak is now fixed. Much appreciated.

**Comment by Ayagikei** [comment]
A little update: In v1.94.0 we tried to change the judgment of task completion streak in **Me** page to be more relaxed (added one day grace period).
