### ISSUE TITLE
[Bug] Force complete item reward splitting

### ISSUE THREAD

**Issue by Hermesiss** [Ayagikei/LifeUp#14]
**Describe the bug**
Force completing a task does not reduce the reward count

**To Reproduce**
1. Create a task
2. Set task type to count 4
3. Add item reward with count of 4
3. Save task
4. Tap a circle to the left to finish a task
5. Set count to 3 and check "Force complete (x0.75 reward)
6. Accept

**Expected behavior**
You should receive 3 reward items instead of 4

**Environments and Version:**
 - Version v1.84.1 (253)

**Additional context**
There can be round options. Like, if 100% will give you 2 items, how many will you get for 25%?

**Comment by Ayagikei** [comment]
Yes. The reward coefficient of the current counting task does not affect the number of items rewarded.

Because we consider that there may be more user scenarios, the number of item rewards will be set to 1. If it is rounded down by default, as long as there is no 100%, it will be 0 item rewards, which may cause confusion.

**We will consider adding an option in a future version.**

**Comment by Ayagikei** [comment]
This option has been rolled out in an update some time ago.
