### ISSUE TITLE
Version without Google Dependence

### ISSUE THREAD

**Issue by Timotia** [Ayagikei/LifeUp#16]
i was hoping that app wasn't dependent on google api 
but when I try to login with in the app then it crash out of no where and I think it has to do with not having google services installed.

**Comment by Ayagikei** [comment]
We have launched an official website version, which will reduce some Google-related dependencies.
However, dependencies such as Google Login, Firebase, etc. will still be retained.

To get this version, you can find it on the [official website](https://wiki.lifeupapp.fun/en/#/introduction/download) or GitHub Release.

This version should be usable outside of the Google environment based on feedback.

**Comment by Ayagikei** [comment]
We will consider the issue closed first.

If you encounter problems, welcome to reopen.

**Comment by nyabinary** [comment]
Is there plans to open source the application at all? Another thing ulives is the 'improved' version of LifeUp is that coming to Android anytime soon?

**Comment by Ayagikei** [comment]
> Is there plans to open source the application at all? Another thing ulives is the 'improved' version of LifeUp is that coming to Android anytime soon?

**There are currently no plans to open-source LifeUp.**

LifeUp is still being actively maintained, and we are continually improving its existing features. Moving forward, we might position LifeUp as a more budget-friendly and open alternative, particularly through its API. Since ulives is a cross-platform product, we are still evaluating how to best introduce similar API functionalities across multiple platforms.

As for bringing ulives to Android, development is already underway. We are working on the Android UI and platform-specific features like Google Drive integration. However, the UI is still being polished, and full regression testing for the features hasn't been completed yet. We are constantly evaluating the Android release schedule—it could launch relatively soon, but it might also be delayed depending on how the remaining testing and polishing go.
