### ISSUE TITLE
[Bug] Make all tasks the same color doesn't use theme color properly

### ISSUE THREAD

**Issue by AkashCherukuri** [Ayagikei/LifeUp#18]
**Describe the bug**
Setting "Make all tasks the same color" doesn't use the theme color, as said by the description.

**To Reproduce**
Check attached video for the bug

**Expected behavior**
Expected the tags to have theme color, have blue instead.

**Video**

https://user-images.githubusercontent.com/62202731/135990753-5b170d00-5653-4d0a-b4ff-7d4769fdd300.mp4

**Environments and Version (please complete the following information):**
 - Device: OnePlus 9
 - Version: Latest from play store

**Comment by Ayagikei** [comment]
Thanks for the report.

The reason for this problem is that the theme color setting is temporarily not supported in night mode.

If night mode is turned off, the problem should not occur.

The theme color we used to replace the library seems to be not suitable for night mode. We tried to adjust it but the effect was not ideal.

This issue needs future follow-up.

**Comment by Ayagikei** [comment]
Sorry for the late update!

**We plan to improve the night mode in v1.90.0.**

In v1.90.0, the night mode will adapt to the theme color and Material You as expected.

**Comment by Ayagikei** [comment]
v1.90 has been released.
