### ISSUE TITLE
[Bug] Countdown timers have been broken for a while now

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#36]
# Describe the bug
Countdown timer notifications (triggered by shop items) will seemingly randomly add large amounts of time to the countdown. The only way to notice this is from seeing that the timer on the notification is far higher than it should be, and there is otherwise no indication that it happened.

# To reproduce
## Steps to reproduce the behavior:
- This seems to occur most often on timers that run for an extended period of time, like 12 hours (input as `720` minutes).
  - You may have to wait a couple hours to see this happen.
- I think that in some cases, pausing and unpausing the timer can also cause the bug to occur, although I can't verify if this is correct.

## Expected behavior
The timer should just run smoothly without this happening.

# Environments and Version
 - Device: Moto z4
 - OS: Android 10
 - App Version: I am currently using version **1.90**, the latest as of this writing, although the bug has been around for significantly longer than that

# Additional context
I don't know if this occurs with the pomodoro timer, but I wouldn't be surprised if it did.

**Comment by Ayagikei** [comment]
Thanks for your feedback, we will reconfirm the issue.

But it needs to be mentioned here that we have fixed a related issue in v1.90.

If it's convincing for you, you can also pay attention to whether the problem occurs again in v1.90.

**Comment by Ayagikei** [comment]
Thanks for the update :D!

**Comment by UsernamesAreNotMyThing** [comment]
I believe I have seen it happen again (1.90.2)

**Comment by Ayagikei** [comment]
> I believe I have seen it happen again (1.90.2)

Thanks for the feedback again. We will check it.

**Comment by Ayagikei** [comment]
In v1.90.3, we made some improvements to this.
You can check to see if it has been fixed.

**Before** the v1.90.3 version, in the case of unexpected process termination, use multi countdown, etc., we may accumulate the timer to the next use (based on the estimated remaining time).
At the same time, due to an abnormal problem, these non-active accumulations will not be displayed in the countdown pop-up window.
But this may indeed not meet the user's expectations, we decided to remove this logic.

**Comment by UsernamesAreNotMyThing** [comment]
This is still occurring in 1.90.3, but now it's *resetting* the timer instead

**Comment by Ayagikei** [comment]
> This is still occurring in 1.90.3, but now it's _resetting_ the timer instead, to where it originally started

Based on these phenomena, **we currently suspect that the system kills the LifeUp process.**
Please make sure you turn off the system and the manufacturer's battery optimization policy when running in the background to ensure that the countdown to LifeUp is calculated correctly.
You can refer to: [https://docs.lifeupapp.fun/en/#/guide/background_running](https://docs.lifeupapp.fun/en/#/guide/background_running)

The issue may be due to [START_REDELIVER_INTENT] of the Android Service.
After the LifeUp process restarts, the original intent is received, causing the timer to reset or accumulate.
**We will try to improve it a bit in the next version. But you should be able to temporarily avoid the problem by doing the above.**

**Comment by UsernamesAreNotMyThing** [comment]
Haven't seen this occur yet in 1.90.4, but I will re-open this if it happens again.

**Comment by UsernamesAreNotMyThing** [comment]
I just had a timer disappear unexpectedly, and the application has no record of it in the "Countdowns" menu

**Comment by Ayagikei** [comment]
> I just had a timer disappear unexpectedly, and the application has no record of it in the "Countdowns" menu

As mentioned above, these are actually exceptions caused by the system unexpectedly stopping the LifeUp process.

Please check your battery optimization settings.

At present, there is no good solution on the application side. But we will try to investigate.

**Comment by UsernamesAreNotMyThing** [comment]
I already have battery optimization disabled for this application on my end.

**Comment by Ayagikei** [comment]
> I already have battery optimization disabled for this application on my end.

Please check [https://dontkillmyapp.com/](https://dontkillmyapp.com/).
In addition to Android's battery optimization options, you'll need to disable additional restrictions from various manufacturers.

**Comment by UsernamesAreNotMyThing** [comment]
My device doesn't fall into any of those brands, so I believe I have done everything I can.

**Comment by Ayagikei** [comment]
Get it.

We will check what we can do on the application side.

UsernamesAreNotMyThing ***@***.***> 于 2022年9月17日周六 11:33写道：

**Comment by UsernamesAreNotMyThing** [comment]
Still occurs in 1.90.7

**Comment by Ayagikei** [comment]
We may need to follow up on this issue in v1.91.0.

At present, this problem is due to the restart of the Service after the system is killed. In theory, it will only appear on some devices and the long countdown. The priority will be medium to low.

Sorry, we need to focus on other higher-priority work items first.
