### ISSUE TITLE
Custom Reset Time

### ISSUE THREAD

**Issue by Denyzn** [Ayagikei/LifeUp#4]
Can you add the option to set a custom time that one day rolls over into the next instead of it defaulting to midnight.

**Comment by Ayagikei** [comment]
Hello. Actually you can set the start/deadline time to the hour. 

For example, you can setup a daily task with start time 1/1 04:00 and deadline time 1/2 04:00.
And it's reset time will be 04:00 instead of 00:00.

We may support the global setting for it in the future.

![image](https://user-images.githubusercontent.com/29143057/103523929-a63e1400-4eb7-11eb-9ac7-1dc14cee16ca.png)
![image](https://user-images.githubusercontent.com/29143057/103523942-ab9b5e80-4eb7-11eb-8840-646d1feec55d.png)

**Comment by Denyzn** [comment]
Thank you for the reply, I do hope to see a global setting in the future
but for now this will do the trick.  Thanks!

**Comment by Ayagikei** [comment]
Sorry for the late update.

We have made some improvemenst on this issues:

- **Added the global settings:**
  [Settings] - [Task Settings] - [New Task Default Settings] - [Default Deadline Time]

- **For specific task:**
  Currently you only need to setup the deadline time, the start time will be calculated by the app.
