### ISSUE TITLE
Feature: Adding and Removing Attributes

### ISSUE THREAD

**Issue by HunterArmstrong** [Ayagikei/LifeUp#9]
In LifeUp, there is a setting where adding and Removing Attributes isn't supported yet. When will adding and removing attributes be supported in LifeUp?

**Comment by Ayagikei** [comment]
Sorry for the late reply.

As we planned, we will start to develop the skills feature (which will be a replacement of attributes and works just like attributes system) after developing the synthesis feature (already working on this) and some other small improvements.

But we can’t provide an accurate time since we're not full-time developing LifeUp.

**Comment by HunterArmstrong** [comment]
Okay. Thanks for the info

**Comment by Ayagikei** [comment]
The feature is available in version 1.84.0.
