### ISSUE TITLE
add_pomodoro does not work with task_id or task_gid 

### ISSUE THREAD

**Issue by vikasmistry** [Ayagikei/LifeUp#92]
**Describe the bug**
When I try to call `add_pomodoro` with `task_id` or `task_gid`, like `http://{host:port}/api?url=lifeup://api/add_pomodoro?task_id=1429&duration=1500000`  I get an error message that says "Required parameter is missing start_time or end_time or duration". However, when I use `lifeup://api/add_pomodoro?task_id=1429&duration=1500000`, it works. When I use `http://{host:port}/api?url=lifeup://api/add_pomodoro?duration=1500000&task_id=1429` I get no error but pomodoro record does not show the task name.

**To Reproduce**
1. Get the `task_id` from Tasks ( my case it is 1429 )
2. Start LifeUp Cloud Service
3. Run `http://192.168.x.x:13276/api?url=lifeup://api/add_pomodoro?task_id=1429&duration=1500000`

**Expected behavior**
The API should accept `task_id` or `task_gid` as parameters and create a new pomodoro.

**Environments and Version (please complete the following information):**
 - Device: Oneplus Nord
 - OS: Android 12
 - LifeUp Version v1.92.2 (287)

**Additional context**
LifeUp Cloud Version 1.3.0

**Comment by Ayagikei** [comment]
Thanks for the issue!

We will look into it.

**Comment by Ayagikei** [comment]
Hello, we have tested the API execution within the application and it should work.

In your case, this seems to be a URL encoding issue.

Take `http://{host:port}/api?url=lifeup://api/add_pomodoro?task_id=1429&duration=1500000` as an example, where `lifeup://api/add_pomodoro?task_id=1429&duration=1500000` is Part of the value belongs to the URL parameter. It contains some special characters (such as `:`, `/`, '&'), so it should be encoded so that the application can properly identify its level.

You can achieve encoding by searching some URL encoding websites or the widgets in our API documentation.

The coded example:
`http://{host:port}/api?url=lifeup%3A%2F%2Fapi%2Fadd_pomodoro%3Ftask_id%3D1429%26duration%3D1500000`

Or you can try the POST method, which reduces one encoding layer.

Also check [https://docs.lifeupapp.fun/en/#/guide/api?id=basics-escaping-url-encode](https://docs.lifeupapp.fun/en/#/guide/api?id=basics-escaping-url-encode) for details.

**Comment by vikasmistry** [comment]
Thank you for providing the solution. As per your suggestion, I updated the URL encoding.
However, it still didn't work  (`http://{host:port}/api?url=lifeup%3A%2F%2Fapi%2Fadd_pomodoro%3Ftask_id%3D1429%26duration%3D1500000`).

Upon re-examining the API documentation, I discovered another URL for a POST request: 

`http://{host:port}/api/contentprovider`. 
(reference: https://docs.lifeupapp.fun/en/#/guide/api_cloud?id=post-method).

Therefore, I modified the URL to 
`http://{host:port}/api/contentprovider?url=lifeup%3A%2F%2Fapi%2Fadd_pomodoro%3Ftask_id%3D1429%26duration%3D1500000`

It is now working as expected.

**Comment by Ayagikei** [comment]
Thanks for your feedback!

The difference between the two may be launching application activities (UI pages) and direct code-level calls.

The former may involve some system restrictions and more permission requirements.

For example, it may require floating window permissions when `LifeUp Cloud` app in the background, and some systems such as MIUI may add additional background restrictions.

We will also continue to check for errors.
