### ISSUE TITLE
[Bug] Coin widget shows weird number after a reboot

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#97]
**Describe the bug**
The number shown on the coin widget appears wrong (apparently a bunch of 2's and 3's) after a reboot, but fixes itself once you go into the app.

**To Reproduce**
Reboot with the widget on your home screen.

**Expected behavior**
I should just show the regular coin number on startup.

**Screenshots**
![Screenshot_20230613-123043](https://github.com/Ayagikei/LifeUp/assets/92757918/1be5bdff-abe6-4900-afd0-ff5ea1782a6a)

**Environments and Version (please complete the following information):**
 - Device: Motorola Moto z4
 - OS: Android 10
 - App Version 1.92.2 (487)

**Additional context**
For some unknown reason, my phone likes to reboot for literally no reason. (no updates happening)

**Comment by Ayagikei** [comment]
Thanks for the report!

This seems to be the default display when the widget is not refreshed to data.

We're not quite sure if this has anything to do with Moto's Launcher, but we'll look into that first.

**Comment by Ayagikei** [comment]
We will change the default displayed value (such as "-") in v1.93.

However, this problem of not refreshing after restarting may be due to a launcher bug or system battery optimization. There's probably nothing we can do about this(?).

Of course, we may introduce mechanisms like WorkManager in the future. This might help a little.
